DEFINES := -DMODEL=system_transmitter -DNUMST=2 -DNCSTATES=6 -DHAVESTDIO 
DEFINES += -DMODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 -DCLASSIC_INTERFACE=0 
DEFINES +=-DALLOCATIONFCN=0 -DTID01EQ=1 -DTERMFCN=1 -DONESTEPFCN=1 
DEFINES += -DMAT_FILE=0 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0

.PHONY: clean

transmitter: *.cpp
	g++ $(DEFINES) $^ -o $@

clean:
	rm -f transmitter